### ISSUE TITLE
Look up time is not constant

### ISSUE THREAD

**Issue by yassersouri** [albertmenglongli/range_many_to_one_dict#1]
Hi, Thanks for sharing this library.

I think it is good to mention in the repo (maybe in the readme) that the look up time on average is not O(1) but O(M) where M is the number of range keys in the dictionary.

**Comment by albertmenglongli** [comment]
Already updated it in the readme.md, thanks

**Comment by albertmenglongli** [comment]
I wrote a new version of RangeKeyDict in pythonic-toolbox, supporting py36, py36+;
The query time is O(log n): https://github.com/albertmenglongli/pythonic-toolbox#rangekeydict
